#include "token_printer.h"

#define stringify_token(tok) \
    [tok + 1] = #tok // enum is indexed from -1 and here we have to index from 0

char* NLANG_TOKEN_NAMES[sizeof(NLANG_TOKEN_TYPE) * 16] = {
    stringify_token(NLANG_INVALID),
    stringify_token(NLANG_PROCEED),
    stringify_token(NLANG_POT_SKIP),
    stringify_token(NLANG_EOF),
    stringify_token(NLANG_INDENT),
    stringify_token(NLANG_COMMENT),
    stringify_token(NLANG_PARENTHESIS_OPEN),
    stringify_token(NLANG_PARENTHESIS_CLOSE),
    stringify_token(NLANG_BRACKET_OPEN),
    stringify_token(NLANG_BRACKET_CLOSE),
    stringify_token(NLANG_SINGLE_QUOTE),
    stringify_token(NLANG_DOUBLE_QUOTE),
    stringify_token(NLANG_FUNC),
    stringify_token(NLANG_IDENTIFIER),
    stringify_token(NLANG_FUNC_PARAM_OPEN),
    stringify_token(NLANG_FUNC_PARAM_CLOSE),
    stringify_token(NLANG_FUNC_PARAM_DECL_OPEN),
    stringify_token(NLANG_FUNC_PARAM_DECL_CLOSE),
    stringify_token(NLANG_EQUALS),
    stringify_token(NLANG_BANG),
    stringify_token(NLANG_NOT_EQUALS),
    stringify_token(NLANG_EQUALSEQUALS),
    stringify_token(NLANG_LESS_THAN),
    stringify_token(NLANG_MORE_THAN),
    stringify_token(NLANG_LESS_OR_EQUAL),
    stringify_token(NLANG_MORE_OR_EQUAL),
    stringify_token(NLANG_KW_IF),
    stringify_token(NLANG_KW_ELSE),
    stringify_token(NLANG_KW_ELSE_IF),
    stringify_token(NLANG_KW_WHILE),
    stringify_token(NLANG_KW_FOR),
    stringify_token(NLANG_KW_THIS),
    stringify_token(NLANG_KW_THAT),
    stringify_token(NLANG_KW_WHEN),
    stringify_token(NLANG_KW_DURING),
    stringify_token(NLANG_KW_TRY),
    stringify_token(NLANG_KW_CATCH),
    stringify_token(NLANG_KW_MATCH),
    stringify_token(NLANG_KW_FN),
    stringify_token(NLANG_KW_ERR),
    stringify_token(NLANG_KW_OK),
    stringify_token(NLANG_KW_SOME),
    stringify_token(NLANG_KW_NONE),
    stringify_token(NLANG_PT_INT),
    stringify_token(NLANG_PT_UINT),
    stringify_token(NLANG_PT_FLOATING),
    stringify_token(NLANG_PT_CHAR),
    stringify_token(NLANG_PT_STRING),
};
